spring:
  application:
    name: gradus
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: vault://
  cloud:
    vault:
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        backend: secret
        default-context: gradus-keyvault
      ssl:
        trust-store: classpath:vault-truststore.jks
        trust-store-password: ${VAULT_TRUST_STORE_PASSWORD}
      uri: https://localhost:8200
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql

jwt:
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
#  access-token-expiration: 30000
#  refresh-token-expiration: 5000
